//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abseentism.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AbseentismEntities : DbContext
    {
        public AbseentismEntities()
            : base("name=AbseentismEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abseentisms> Abseentisms { get; set; }
        public virtual DbSet<AbsenceTypes> AbsenceTypes { get; set; }
        public virtual DbSet<Agents> Agents { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
    }
}
