//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abseentism.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abseentisms
    {
        public Nullable<int> AgentId { get; set; }
        public Nullable<int> AbsenceId { get; set; }
        public Nullable<System.TimeSpan> currentSchedule { get; set; }
        public Nullable<System.TimeSpan> newSchedule { get; set; }
        public Nullable<System.DateTime> dateNewSchedule { get; set; }
        public string reasonOfChange { get; set; }
        public Nullable<System.DateTime> absentDate { get; set; }
        public Nullable<System.DateTime> lateDate { get; set; }
        public string lateReason { get; set; }
        public Nullable<System.TimeSpan> lateOriginalTime { get; set; }
        public Nullable<System.TimeSpan> lateActualTime { get; set; }
        public int id { get; set; }
    
        public virtual AbsenceTypes AbsenceTypes { get; set; }
        public virtual Agents Agents { get; set; }
    }
}
